// export default {
// 	LOGIN_REQUEST: 'LOGIN_REQUEST',
// 	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
// 	LOGIN_FAILED: 'LOGIN_FAILED',
// 	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
// 	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
// 	LOGOUT_FAILED: 'LOGOUT_FAILED'
// };


export default {
	login: {
		LOGIN_REQUEST: 'LOGIN_REQUEST',
		LOGIN_SUCCESS: 'LOGIN_SUCCESS',
		LOGIN_FAILED: 'LOGIN_FAILED',
		LOGOUT_REQUEST: 'LOGOUT_REQUEST',
		LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
		LOGOUT_FAILED: 'LOGOUT_FAILED'
	},
	packages: {
		SET_TREE_IS_ACTIVE: 'SET_TREE_IS_ACTIVE',
		SET_HISTORY_IS_ACTIVE: 'SET_HISTORY_IS_ACTIVE',
		SET_TREE_IS_LOADING: 'SET_TREE_IS_LOADING',
		SET_HISTORY_IS_LOADING: 'SET_HISTORY_IS_LOADING',
		SET_VERSION_TREE: 'SET_VERSION_TREE',
		APPEND_VERSION_HISTORY: 'APPEND_VERSION_HISTORY',
	}
};
